// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6hM3TlVJfw3Dz7SyqxoW05A7WGokVj8',
    appId: '1:675680750592:web:6321d1d78955f3b32a9ce5',
    messagingSenderId: '675680750592',
    projectId: 'lojavirtual2-ddbda',
    authDomain: 'lojavirtual2-ddbda.firebaseapp.com',
    storageBucket: 'lojavirtual2-ddbda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGdhN9mS1dr6uC1AneXe1xqOynAJVVJc',
    appId: '1:675680750592:android:8af3787b657a9f152a9ce5',
    messagingSenderId: '675680750592',
    projectId: 'lojavirtual2-ddbda',
    storageBucket: 'lojavirtual2-ddbda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6zxMfT0R3qhAr4Pm-bn0N1HVKF4S87MQ',
    appId: '1:675680750592:ios:0e46d4fb8f8c9c972a9ce5',
    messagingSenderId: '675680750592',
    projectId: 'lojavirtual2-ddbda',
    storageBucket: 'lojavirtual2-ddbda.appspot.com',
    iosClientId: '675680750592-qgouhbi5as2gefdvh1bum6ifle75c5oo.apps.googleusercontent.com',
    iosBundleId: 'br.com.olhachei.lojaVirtual2',
  );
}
